# Generated by Django 3.2.18 on 2023-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230407_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(to='core.Like'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
