# Generated by Django 3.2.18 on 2023-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230407_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
