# Generated by Django 3.2.18 on 2023-04-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230410_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes_count',
            new_name='the_like',
        ),
    ]
