# Generated by Django 3.2.18 on 2023-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='time_create_at',
        ),
        migrations.AddField(
            model_name='like',
            name='the_like',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(default=None, null=True, related_name='likes', to='core.Like'),
        ),
    ]
