# Generated by Django 3.2.18 on 2023-04-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230411_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='likes', to='core.Like'),
        ),
    ]
